// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"0hock5jff6","name":"sampleCloudApi","description":"","endpoint":"https://0hock5jff6.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/items","/items/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:092c48fd-801e-4fa3-990a-fc14a57bac7d',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'goalsaver-hosting-mobilehub-1686680927',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd31jgi0k3u8ht.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-east-1',
    'aws_dynamodb_table_schemas': [{"tableName":"goalsaver-mobilehub-1686680927-AWSMobileTable","attributes":[{"name":"teamId","type":"S"},{"name":"personId","type":"S"},{"name":"email","type":"S"},{"name":"personName","type":"S"},{"name":"phone","type":"S"}],"indexes":[{"indexName":"personName-index","hashKey":"teamId","rangeKey":"personName"}],"region":"us-east-1","hashKey":"teamId","rangeKey":"personId"}],
    'aws_mobile_analytics_app_id': 'f09a3f20b8124f25b1388673506be900',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'ee958e53-248e-4646-a5ba-0b3d90863221',
    'aws_project_name': 'GoalSaver-2018-08-07-11-08-28',
    'aws_project_region': 'us-east-1',
    'aws_resource_bucket_name': 'goalsaver-deployments-mobilehub-1686680927',
    'aws_resource_name_prefix': 'goalsaver-mobilehub-1686680927',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'goalsaver-userfiles-mobilehub-1686680927',
    'aws_user_files_s3_bucket_region': 'us-east-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_XbFz5B1UF',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '6vmmmk69fvhp9dcu1btcja3d56',
    'aws_appsync_graphqlEndpoint': 'https://vc37ogm4yfa3rh4lky7xxf4gwa.appsync-api.us-east-1.amazonaws.com/graphql',
    'aws_appsync_region': 'us-east-1',
    'aws_appsync_authenticationType': 'AWS_IAM',
}

export default awsmobile;
